rm -rf CaM-N.pqr
rm -rf pCaN.pqr
rm -rf CaM-N-atoms.xml
rm -rf pCaN-atoms.xml
rm -rf CaM-N-pCaN-solvent.xml
rm -rf CaM-N.dx
rm -rf CaM_N.apbslog
rm -rf pCaN.dx
rm -rf pCaN.apbslog
rm -rf io.mc
rm -rf pCaN-charges.xml
rm -rf pCaN-cheby.xml
rm -rf pCaN-surface.xml
rm -rf ins-pCaN.xml
rm -rf born-pCaN.dx
rm -rf pCaN-q2.xml
rm -rf pCaN-q2-cheby.xml
rm -rf pCaN-volume.xml
rm -rf pCaN-ellipsoids.xml
rm -rf CaM-N-pCaN-pairs.xml
rm -rf CaM-N-pCaN-rxns.xml
rm -rf pCaN-surface-atoms-hard.xml
rm -rf pCaN-surface-atoms.xml
rm -rf CaM-N-surface.xml
rm -rf ins-CaM-N.xml
rm -rf born-CaM-N.dx
rm -rf CaM-N-charges.xml
rm -rf CaM-N-q2.xml
rm -rf CaM-N-q2-cheby.xml
rm -rf CaM-N-volume.xml
rm -rf CaM-N-ellipsoids.xml
rm -rf CaM-N-surface-atoms-hard.xml
rm -rf CaM-N-surface-atoms.xml
rm -rf CaM-N-hydro-radius.xml
rm -rf pCaN-hydro-radius.xml
rm -rf CaM-N-mpole.xml
rm -rf pCaN-mpole.xml
rm -rf CaM-N-pCaN-return-dist.xml
rm -rf CaM-N-pCaN-simulation.xml
rm -rf CaM-N-pCaN-old-data.xml
rm -rf traj5.index.xml
rm -rf traj3.index.xml
rm -rf traj6.index.xml
rm -rf traj2.index.xml
rm -rf traj8.index.xml
rm -rf traj4.index.xml
rm -rf traj3.xml
rm -rf traj7.index.xml
rm -rf traj5.xml
rm -rf traj0.index.xml
rm -rf traj8.xml
rm -rf traj4.xml
rm -rf traj2.xml
rm -rf traj6.xml
rm -rf traj0.xml
rm -rf traj9.xml
rm -rf traj9.index.xml
rm -rf traj7.xml
rm -rf traj1.xml
rm -rf traj1.index.xml
rm -rf results.xml
