#!/bin/bash
#SBATCH -p limited # partition (queue) for CHE580 
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=4
#SBATCH --time=1:00:00
#SBATCH --job-name=fancypants  


module load apbs/1.4.2
module load pdb2pqr/2.1.1
module load browndye/5Dec2016


#-----------------------------------------------------------------
# Step 1: convert pdbqr file generated by pdb2pqr to .xml format which 
#         is the native format used in BD sims
#----------------------------------------------------------------
for i in CaM-N pCaN
do         
         pqr2xml < ${i}.pqr > ${i}-atoms.xml
done


#-------------------------------------------------------------------------
# Step 2: a) identify the interacting residue-residue pairs
#         b) specify the reaction criterion, in this case: 4 pairs of reaction with
#            distance cutoff being 4 A
make_rxn_pairs -mol0 CaM-N-atoms.xml -mol1 pCaN-atoms.xml -ctypes protein-protein-contacts.xml -dist 5 > CaM-N-pCaN-pairs.xml
make_rxn_file -pairs CaM-N-pCaN-pairs.xml -distance 4.5 -nneeded 4 > CaM-N-pCaN-rxns.xml



#-------------------------------------------------------------------------
# Step 3: calculate the electrostatic potential of these two parts
#         (take a look at CaM_N.in/pCaN.in files for parameters used
#          in the apbs calculations)
#
#      !!!!! 3a) Here we set the ionic strength as 1.028 M [NaCl], you can 
#      !!!!! chnage the values in the .in file
#      !!!!! 3b) After the apbs calculations, open one of the .apbslog files
#      !!!!! to get the vaule of Debye length at this ionic strength, in this
#      !!!!! case, the Debye length is 2.99 A at 1.028 M [NaCl]
#      !!!!! 3c) Put the Debye length value in "input.xml" file in Step 4, in this
#      !!!!! tutoral the correct values has been typed into "input.xml"
#----------------------------------------------------------------
apbs CaM-N.in > CaM_N.apbslog
apbs pCaN.in > pCaN.apbslog


#-----------------------------------------------------
# Step 4: generate the input file for BD simulations
#         (the important parameter is the Debye length from Step 3,
#         you can also change # of procs and # of trajectories in "input.xml",
#         in current tutorial, we use 10 procs and 10000 trajectoris for 
#         each simulation.)
#---------------------------------------------------
# 
bd_top input.xml

#------------------------------------------
# Step 5: run BD simulations
#--------------------------------------------
nam_simulation CaM-N-pCaN-simulation.xml


#-----------------------------------------------------
# Step 6: get association rates and store in log file
#----------------------------------------------------
compute_rate_constant < results.xml > log

